/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData leaf = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_convenience_store = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hands_wash = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carrot = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggplant = IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meat = IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toast = IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_alt = IconData(0xf5d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candy_cane = IconData(0xf786, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
